
modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory
license="SoulHome License"

[[mods]] #mandatory
modId="soulhome" #mandatory
version="${file.jarVersion}"
displayName="SoulHome" #mandatory
logoFile="soulhome.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="Leaf Reynolds" #optional
description='''
This is a long form description of the mod. You can write whatever you want here
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.soulhome]] #optional
    modId="forge"
    mandatory=true
    versionRange="[39.0.44,)"
